name: Build and test

on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      deployment_stage:
        required: false
        type: string
      wants_artifacts:
        required: false
        type: boolean
        default: false

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment_stage }}
    env:
      APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
      AUTH_GW_BASE_URL: ${{ secrets.AUTH_GW_BASE_URL }}
      USER_API_BASE_URL: ${{ secrets.USER_API_BASE_URL }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: App install, test
        run: |
          npm install
          npm test
      - name: App build
        if: ${{ inputs.deployment_stage }}
        run: npm build
      - name: Archive the build artifacts
        if: ${{ inputs.wants_artifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-${{ inputs.deployment_stage }}
          path: build
          retention-days: 1
          if-no-files-found: error
