name: Build and test

on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      deployment_stage:
        required: false
        type: string
      wants_artifacts:
        required: false
        type: boolean
        default: false
      # app_base_url:
      # required: false
      # type: string
      # auth_gw_base_url:
      #required: false
      # type: string
      # user_api_base_url:
      # required: false
      # type: string
    secrets:
      APP_BASE_URL:
        required: true
      AUTH_GW_BASE_URL:
        required: true
      USER_API_BASE_URL:
        required: true

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment_stage }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: App install, test
        run: |
          npm install
          npm test
      - name: App build
        if: ${{ inputs.deployment_stage }}
        run: npm run build
        env:
          REACT_APP_APPLICATION_BASE_URL: ${{ secrets.APP_BASE_URL }}
          REACT_APP_AUTH_GW_BASE_URL: ${{ secrets.AUTH_GW_BASE_URL }}
          REACT_APP_USER_API_BASE_URL: ${{ secrets.USER_API_BASE_URL }}
      - name: Archive the build artifacts
        if: ${{ inputs.wants_artifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-${{ inputs.deployment_stage }}
          path: build
          retention-days: 1
          if-no-files-found: error
