name: Build and test

on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      deployment_stage:
        required: false
        type: string
      wants_artifacts:
        required: false
        type: boolean
        default: false

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment_stage }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: App install, test
        run: |
          npm install
          npm test
      # testing pulumi outputs action
      - name: Testing pulumi outputs actions
        uses: Virtual-Finland-Development/pulumi-outputs-action@v1
        id: pulumi-outputs-test
        with:
          pulumi-organization: 'virtualfinland'
          pulumi-project: 'authentication-gw'
          pulumi-stack: 'dev'
          pulumi-resource: 'endpoint'
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      # /testing pulumi outputs action
      - name: App build
        if: ${{ inputs.deployment_stage }}
        run: npm run build
        env:
          REACT_APP_AUTH_GW_BASE_URL: ${{ secrets.AUTH_GW_BASE_URL }}
          REACT_APP_USER_API_BASE_URL: ${{ secrets.USER_API_BASE_URL }}
          REACT_APP_EXT_REGISTRATION_SERVICE_URL: ${{ secrets.EXT_REGISTRATION_SERVICE_URL }}
          REACT_APP_TESTBED_API_BASE_URL: ${{ secrets.TESTBED_API_BASE_URL }}
          REACT_APP_PULUMI_OUTPUTS_TEST: ${{ steps.pulumi-outputs-test.outputs.resource-output }}
      - name: Archive the build artifacts
        if: ${{ inputs.wants_artifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-${{ inputs.deployment_stage }}
          path: build
          retention-days: 1
          if-no-files-found: error
