name: Deploy Staging

on:
  workflow_dispatch:
    branches: ['main']

jobs:
  deploy:
    uses: Virtual-Finland-Development/access-to-finland-demo-front/.github/workflows/deployment.yml@main
    with:
      deployment_stage: staging
    secrets: inherit
