name: Deploy Dev

on:
  push:
    branches: ['main']

jobs:
  deploy:
    uses: Virtual-Finland-Development/access-to-finland-demo-front/.github/workflows/deployment.yml@main
    with:
      deployment_stage: dev
    secrets: inherit
