name: Deploy Staging

on:
  workflow_dispatch:
    branches: ['main']

jobs:
  deploy:
    uses: Virtual-Finland-Development/access-to-finland-demo-front/.github/workflows/deployment.yml@main
    with:
      deployment_stage: staging
      app_base_url: ${{ secrets.APP_BASE_URL_STAGING }}
      auth_gw_base_url: ${{ secrets.AUTH_GW_BASE_URL_STAGING }}
      user_api_base_url: ${{ secrets.USER_API_BASE_URL_STAGING }}
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
