name: Deploy a stage

on:
  workflow_call:
    inputs:
      deployment_stage:
        required: true
        type: string

env:
  pulumi_stack_organization: virtualfinland
  aws_region: eu-north-1

jobs:
  build-and-test:
    uses: Virtual-Finland-Development/access-to-finland-demo-front/.github/workflows/build-and-test.yml@main
    with:
      deployment_stage: ${{ inputs.deployment_stage }}
      wants_artifacts: true
    secrets: inherit
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Download the built artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact-${{ inputs.deployment_stage }}
          path: ./build
      - name: Display structure of downloaded artifact files
        run: |
          ls -R build
      - name: Configure AWS credentials
        uses: Virtual-Finland-Development/infrastructure/.github/actions/configure-aws-credentials@main
        with:
          environment: ${{ inputs.deployment_stage }}
          aws-region: ${{ secrets.AWS_REGION }}
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Pulumi install, test
        working-directory: ./infra
        run: |
          npm install
          npm test
      - name: Deploy with Pulumi
        uses: pulumi/actions@v4
        with:
          work-dir: ./infra
          command: up
          stack-name: ${{ env.pulumi_stack_organization }}/${{ inputs.deployment_stage }}
          upsert: true # create stack if no exists
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Tag the deployment
        uses: Virtual-Finland-Development/automatic-release-action@v1.0
        if: ${{ inputs.deployment_stage == 'staging' }}
        with:
          environment: ${{ inputs.deployment_stage }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
