name: Build, test, deploy - Staging
on:
  workflow_dispatch:
jobs:
  deploy-staging:
    name: Deploy staging
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: 'eu-north-1'
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install app dependencies
        run: npm install
      - name: Run app tests
        run: npm test
      - name: Build app
        run: npm run build:staging

      - name: Install Pulumi dependencies
        working-directory: ./infra
        run: npm install
      - name: Run pulumi tests
        working-directory: ./infra
        run: npm test
      - name: Deploy with Pulumi
        uses: pulumi/actions@v3
        with:
          work-dir: ./infra
          command: up
          stack-name: virtualfinland/staging
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
